session_name: sdl2-playproject
start_directory: ./ # load session relative to config location (project root).
windows:
- window_name: sdl2-playproject
  focus: True
  layout: main-horizontal
  options:
    main-pane-height: 35
  panes:
  - focus: true
  - pane 
  - pane 
  - ls src/*.{c,h} | entr make debug_ninja
