session_name: sdl2-playproject
start_directory: ./ # load session relative to config location (project root).
windows:
- window_name: sdl2-playproject
  focus: True
  layout: main-horizontal
  options:
    main-pane-height: 35
  panes:
  - focus: true
  - pane 
  - pane 
  - if command -v entr > /dev/null; then find . -type f -not -path '*/\.*' | grep -i '.*[.][cpp,h]$' | entr -c make debug_ninja; else make debug_ninja; echo "\nInstall entr(1) to automatically run tests on file change.\n See http://entrproject.org/"; fi
